### ISSUE TITLE
Unit Test Failed

### ISSUE THREAD

**Issue by bornlibra23** [wo3kie/assocVector#4]
Hi Any Suggestions?
Is the library still good?

[root@localhost assocVector]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
[root@localhost assocVector]# make
g++ --std=c++11 -g -ggdb unit.test.cpp -o ut
g++ --std=c++11 -g -ggdb  -DNDEBUG perf.test.cpp -o pt
[root@localhost assocVector]# gdb ut
(gdb) run
Starting program: /media/sf_Libraries/assocVector/ut
Util tests...OK.
Core tests...OK.
Iterator tests...OK.
C++11x tests...(1021) == 0

Program received signal SIGSEGV, Segmentation fault.
0x0000000000414840 in cxx11x_move_test_1 () at unit.test.cpp:2988
2988            AV_ASSERT_EQUAL( Value::copies, 0 );
Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64
(gdb) bt
#0  0x0000000000414840 in cxx11x_move_test_1 () at unit.test.cpp:2988
#1  0x0000000000416d68 in main (argc=1, argv=0x7fffffffe568) at unit.test.cpp:3339
(gdb) p Value::copies
$1 = 1021
(gdb) q

**Comment by wo3kie** [comment]
Thank you for your message. Most of unit tests are correct, unfortunately C++11 with Move Semantic is failing. It means that extra copies are made unnecessarily. Although I am not developing this library anymore, I will take a look at this.
